# إعدادات النظام الأساسية
app:
  server_name: "0.0.0.0"
  server_port: 7860
  share_gradio_link: false
  max_threads: 8  # مناسب لمعالج Xeon ثنائي النواة
  auth_user: ""  # اترك فارغاً لتعطيل المصادقة
  auth_pass: ""

# إعدادات محرك TTS
tts_engine:
  use_gpu: true
  use_half_precision: true  # تفعيل للـ RTX 3060
  batch_size: 4  # يمكن زيادتها مع 32GB RAM
  use_deepspeed: true
  kv_cache: true
  device: "cuda"
  num_workers: 4
  memory_efficient: false  # يمكن تعطيلها مع 32GB RAM

# إعدادات الصوت
audio:
  sample_rate: 24000
  silence_threshold: -40.0
  normalize_db: -3.0
  channels: 1
  bit_depth: 16

# المسارات الرئيسية
directories:
  voices: "voices"
  output: "output"
  models: "models"
  cache: "cache"

# إعدادات التسجيل
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"
  max_size: 10485760  # 10 ميجابايت
  backup_count: 5

# إعدادات GPU
gpu:
  memory_limit: 10240  # 10GB من 12GB المتوفرة
  clear_cache: true
  power_saving: false
  cudnn_benchmark: true
  deterministic: false
  allow_tf32: true  # متوفر على RTX 3060